#!/usr/bin/env zsh

meteo () {
    tput reset

    DateColumn=28
    TimeColumn=17

    weather_output=$(curl https://wttr.in/YKF\?0mf --silent --max-time 3)
    echo "$weather_output" > /tmp/now-weather

# options (https://wttr.in/:help)
        #  0  -> View: only current weather
        #  m  -> Units: metric (SI) (default everywhere except US)
    #  f  -> View: do not show the "Follow" line

    if [[ $weather_output == "Weather report:"* ]]; then
        WeatherSuccess=true
        echo -e "\n $weather_output"
    else
        WeatherSuccess=false
        echo "+=====================+"
        echo "|                     |"
        echo "|                     |"
        echo "| Weather Unavailable |"
        echo "|                     |"
        echo "|                     |"
        echo "+=====================+"
        echo " "
    fi

    tput sc

    i=0
    while (( ++i < 10 )); do
        tput cuu1
    done

    if [[ $WeatherSuccess == true ]]; then
        Column=$(( DateColumn - 8 ))
        tput cuf "$Column"
        printf "          "
    else
        tput cuf "$DateColumn"
    fi

    cal > /tmp/terminal1
    tr -cd '\11\12\15\40\60-\136\140-\176' < /tmp/terminal1 > /tmp/terminal

    CalLineCnt=1
    Today=$(date +%e)  # %e instead of %d to avoid leading zero
    Test=${Test// /}   # Remove spaces
    TodayInt=$((10#$Today)) # Force Today to be an integer

    printf "\033[34m"

    while IFS= read -r Cal; do
        printf "%s" "$Cal"

        if (( CalLineCnt > 2 )); then
            tput cub 22

            for (( j = 0; j <= 18; j += 3 )); do
                Test=${Cal[*]:$j:2}
                TestInt=$((10#$Test)) # Force Test to be an integer

                if (( TestInt == TodayInt )) ; then # Integer Comparison
                    printf "\033[0;32m\033[7m%2d" "$TodayInt" # Use %2d for consistent spacing
                    printf "\033[0m\033[34m"
                    tput cuf 1
                else
                    tput cuf 3
                fi
            done
        fi

        tput cud1
        tput cuf "$DateColumn"
        (( CalLineCnt++ ))
    done < /tmp/terminal

    printf "\033[00m"

    tput rc

    tput sc

    i=0
    while (( ++i < 9 )); do
        tput cuu1
    done

    tput cuf "$TimeColumn"
    date +"%H:%M" > /tmp/terminal

    while IFS= read -r Time; do
        printf "\033[0;32m\033[7m%s" "$Time"
        tput cud1
        tput cuf "$TimeColumn"
    done < /tmp/terminal

    tput rc
    printf "\n"

    \rm -f /tmp/now-weather /tmp/terminal1 /tmp/terminal
}

# ^ 2023-05-18T13:07:04-0500\
# % 2024-10-16T23:52:17-0400
